"""Tests for the linux_vitals_cert_facts module and the vitals_certs findings.

The module is exercised against real certificates generated by `openssl` into
a temporary directory, rather than against recorded fixtures, because the
thing most likely to break is the parsing of `openssl`'s own output -- and a
fixture would freeze whatever that looked like on the machine the fixture was
captured on.

Tests that need `openssl` skip when it is absent rather than fail; the module
already degrades to "no certificates" on such a host, which is asserted
separately.

See issue #15.
"""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

from test_templates import REPO_ROOT, _ansible_playbook_bin, _base_env

CERTS_TASKS = REPO_ROOT / "roles" / "vitals_certs" / "tasks" / "main.yml"
CERTS_DEFAULTS = REPO_ROOT / "roles" / "vitals_certs" / "defaults" / "main.yml"

openssl_required = pytest.mark.skipif(
    shutil.which("openssl") is None,
    reason="openssl is not installed on this machine",
)


def _make_cert(directory: Path, name: str, days: int, *, digest: str = "sha256",
               common_name: str = "example.test") -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / name
    subprocess.run(
        [
            "openssl", "req", "-x509",
            f"-{digest}",
            "-newkey", "rsa:2048",
            "-keyout", str(directory / f"{name}.key"),
            "-out", str(path),
            "-days", str(days),
            "-nodes",
            "-subj", f"/CN={common_name}",
        ],
        check=True,
        capture_output=True,
    )
    return path


def _run_module(tmp_path: Path, **params) -> dict:
    task = {
        "name": "Collect certificate facts",
        "sameeralam3127.linux_vitals.linux_vitals_cert_facts": params,
        "register": "facts",
    }
    dump = {
        "name": "Write results for assertion",
        "ansible.builtin.copy": {
            "content": "{{ facts | to_nice_json }}\n",
            "dest": "{{ output_dir }}/cert_facts.json",
            "mode": "0644",
        },
    }
    playbook = [
        {
            "name": "Exercise linux_vitals_cert_facts",
            "hosts": "localhost",
            "connection": "local",
            "gather_facts": False,
            "vars": {
                "output_dir": "{{ lookup('ansible.builtin.env', 'TEST_OUTPUT_DIR') }}"
            },
            "tasks": [task, dump],
        }
    ]
    path = tmp_path / "cert_facts_case.yml"
    path.write_text(yaml.safe_dump(playbook, sort_keys=False), encoding="utf-8")
    subprocess.run(
        [_ansible_playbook_bin(), str(path)],
        check=True,
        cwd=REPO_ROOT,
        env=_base_env(tmp_path),
    )
    return json.loads((tmp_path / "cert_facts.json").read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Module: filesystem scanning
# ---------------------------------------------------------------------------

@openssl_required
def test_a_certificate_on_disk_is_parsed_with_its_expiry(tmp_path: Path) -> None:
    certs = tmp_path / "certs"
    _make_cert(certs, "web.crt", days=400, common_name="web.example.test")

    result = _run_module(tmp_path, paths=[str(certs)])

    assert result["openssl_available"] is True
    found = [c for c in result["certificates"] if c["path"].endswith("web.crt")]
    assert len(found) == 1
    cert = found[0]
    assert "web.example.test" in cert["subject"]
    assert cert["expired"] is False
    # openssl dates are whole days and the comparison is against "now", so the
    # count lands on 399 or 400 depending on the second the test runs.
    assert 395 <= cert["days_remaining"] <= 400
    assert cert["self_signed"] is True
    assert cert["fingerprint_sha256"].count(":") == 31


@openssl_required
def test_an_expired_certificate_is_reported_as_expired(tmp_path: Path) -> None:
    # Issued with a validity window entirely in the past, which is the only
    # way to get openssl to produce an already-expired certificate.
    certs = tmp_path / "certs"
    certs.mkdir(parents=True, exist_ok=True)
    path = certs / "expired.crt"
    subprocess.run(
        [
            "openssl", "req", "-x509", "-newkey", "rsa:2048",
            "-keyout", str(certs / "expired.key"),
            "-out", str(path),
            "-not_before", "20200101000000Z",
            "-not_after", "20200201000000Z",
            "-nodes", "-subj", "/CN=expired.example.test",
        ],
        check=True,
        capture_output=True,
    )

    result = _run_module(tmp_path, paths=[str(certs)])

    cert = next(c for c in result["certificates"] if c["path"].endswith("expired.crt"))
    assert cert["expired"] is True
    assert cert["days_remaining"] < 0, "an expired certificate must count down past zero"


@openssl_required
def test_a_private_key_matching_the_patterns_is_skipped_not_reported(
    tmp_path: Path,
) -> None:
    # The default patterns match *.pem, and a letsencrypt live/ directory is
    # mostly privkey.pem. Reporting those as broken certificates would
    # manufacture a finding per host per renewal directory.
    certs = tmp_path / "certs"
    _make_cert(certs, "real.pem", days=100)
    (certs / "privkey.pem").write_text(
        "-----BEGIN PRIVATE KEY-----\nnotacert\n-----END PRIVATE KEY-----\n",
        encoding="utf-8",
    )

    result = _run_module(tmp_path, paths=[str(certs)], file_patterns=["*.pem"])

    paths = [c["path"] for c in result["certificates"]]
    assert any(p.endswith("real.pem") for p in paths)
    assert not any(p.endswith("privkey.pem") for p in paths)


@openssl_required
def test_a_weak_signature_algorithm_is_reported(tmp_path: Path) -> None:
    certs = tmp_path / "certs"
    _make_cert(certs, "weak.crt", days=200, digest="sha1")

    result = _run_module(tmp_path, paths=[str(certs)])

    cert = next(c for c in result["certificates"] if c["path"].endswith("weak.crt"))
    assert "sha1" in cert["signature_algorithm"].lower()


def test_a_missing_path_is_skipped_rather_than_failing_the_run(
    tmp_path: Path,
) -> None:
    # A cert directory that does not exist on a given host is the normal case
    # in a mixed fleet, not an error.
    result = _run_module(tmp_path, paths=["/nonexistent/certificates"])

    assert result["certificates"] == []
    assert result["scanned_paths"] == []
    # The module returned data rather than failing the task, which is the point.
    assert result["failed"] is False


@openssl_required
def test_max_depth_bounds_the_search(tmp_path: Path) -> None:
    certs = tmp_path / "certs"
    _make_cert(certs / "a" / "b" / "c", "deep.crt", days=100)
    _make_cert(certs, "shallow.crt", days=100)

    shallow = _run_module(tmp_path, paths=[str(certs)], max_depth=1)
    deep = _run_module(tmp_path, paths=[str(certs)], max_depth=5)

    shallow_paths = [c["path"] for c in shallow["certificates"]]
    deep_paths = [c["path"] for c in deep["certificates"]]
    assert any(p.endswith("shallow.crt") for p in shallow_paths)
    assert not any(p.endswith("deep.crt") for p in shallow_paths)
    assert any(p.endswith("deep.crt") for p in deep_paths)


# ---------------------------------------------------------------------------
# Module: endpoints
# ---------------------------------------------------------------------------

def test_an_unreachable_endpoint_is_reported_as_data_not_a_failure(
    tmp_path: Path,
) -> None:
    # Port 1 on localhost: refused immediately, so this needs no network and
    # cannot hang CI.
    result = _run_module(
        tmp_path,
        paths=[],
        endpoints=[{"host": "127.0.0.1", "port": 1}],
        timeout=2,
    )

    assert len(result["endpoints"]) == 1
    endpoint = result["endpoints"][0]
    assert endpoint["host"] == "127.0.0.1"
    assert "error" in endpoint
    assert endpoint["not_after"] is None


def test_an_endpoint_without_a_host_is_reported_not_crashed(
    tmp_path: Path,
) -> None:
    result = _run_module(tmp_path, paths=[], endpoints=[{"port": 443}])

    assert result["endpoints"][0]["error"] == "endpoint has no host"


# ---------------------------------------------------------------------------
# Role: the defaults and the findings they drive
# ---------------------------------------------------------------------------

def test_the_role_is_opt_in() -> None:
    defaults = yaml.safe_load(CERTS_DEFAULTS.read_text(encoding="utf-8"))

    assert defaults["linux_vitals_certs_enabled"] is False
    # Enabling the role must not start scanning the network.
    assert defaults["linux_vitals_cert_endpoints"] == []


def test_the_critical_window_is_inside_the_warning_window() -> None:
    defaults = yaml.safe_load(CERTS_DEFAULTS.read_text(encoding="utf-8"))

    assert (
        defaults["linux_vitals_cert_critical_days"]
        < defaults["linux_vitals_cert_warning_days"]
    ), "a critical window wider than the warning window can never fire"


def test_every_task_is_gated_on_the_opt_in_switch() -> None:
    document = yaml.safe_load(CERTS_TASKS.read_text(encoding="utf-8"))

    assert len(document) == 1, "tasks/main.yml should be one gated block"
    top = document[0]
    assert top["when"] == "linux_vitals_certs_enabled | bool"
    assert "certs" in top["tags"]
    assert "block" in top


def test_the_trust_store_is_excluded_from_expiry_reporting_by_default() -> None:
    # The system CA bundle is hundreds of root certificates that are not
    # yours, several of which are always near expiry. Reporting on them would
    # bury every real finding.
    defaults = yaml.safe_load(CERTS_DEFAULTS.read_text(encoding="utf-8"))

    trust = defaults["linux_vitals_cert_trust_store_paths"]
    assert "/etc/ssl/certs" in trust
    # ...but it is still scanned, so an expired cert in the bundle is visible.
    assert "/etc/ssl/certs" in defaults["linux_vitals_cert_fs_paths"]
