---
- name: Build required service status map
  ansible.builtin.set_fact:
    linux_vitals_service_status:
      sssd:
        service_name: >-
          {{
            (
              ['sssd.service', 'sssd']
              | select('in', ansible_facts.services.keys() | list) | list
              | first
            ) | default('absent', true)
          }}
        state: >-
          {{
            ansible_facts.services.get(
              (
                ['sssd.service', 'sssd']
                | select('in', ansible_facts.services.keys() | list) | list
                | first
              ) | default('absent', true),
              {}
            ).state | default('missing')
          }}
      systemd_journald:
        service_name: >-
          {{
            (
              ['systemd-journald.service', 'systemd-journald']
              | select('in', ansible_facts.services.keys() | list) | list
              | first
            ) | default('absent', true)
          }}
        state: >-
          {{
            ansible_facts.services.get(
              (
                ['systemd-journald.service', 'systemd-journald']
                | select('in', ansible_facts.services.keys() | list) | list
                | first
              ) | default('absent', true),
              {}
            ).state | default('missing')
          }}
      time_sync:
        service_name: "{{ linux_vitals_time_sync_service }}"
        state: >-
          {{
            ansible_facts.services.get(
              linux_vitals_time_sync_service,
              {}
            ).state | default('missing')
          }}
  tags:
    - discovery
